### PR TITLE
Add --no-cov to vscode test launch config to make debugging work

### PR DESCRIPTION
**Pull request by GDYendell**

### CODE REVIEW

**Comment by GDYendell** [comment]
I think this was lost in the conversion from the skeleton, unless it was removed for a reason?

**Review by DominicOram — APPROVED** [review]
Great, thank you!

**Comment by coretl** [comment]
It was removed from the pytest default ini args (in pyproject.toml) and inserted in tox:
https://github.com/DiamondLightSource/python-copier-template/blob/3462fe957ee1f1e2c9495b413a965719f3103460/template/pyproject.toml.jinja#L97

This means that you only get coverage if you do `tox -e tests`, so vscode launch config shouldn't be needed...

**Comment by GDYendell** [comment]
Ahh, yes OK that does work for me. In which case @DominicOram you just need to update to the latest copier and it should work.

**Pull request closed without merging**
