### PR TITLE
Minor cleanups

### PR DESCRIPTION
**Pull request by joeshannon**
* Delete git_merge.png
  This looks like a left over artifact from the skeleton project.
* Remove reference to plot_spec.png
  This likely leaked in from the scanspec project.

### CODE REVIEW

**Comment by joeshannon** [comment]
I'm not really sure why the tests are failing, seemed to work locally.

**Comment by GDYendell** [comment]
The type of error has changed?

https://github.com/DiamondLightSource/python-copier-template/blob/main/tests/test_example.py#L77

**Comment by joeshannon** [comment]
> The type of error has changed?
Yes interesting I made a new venv and main is failing locally with the same for me now.

**Comment by joeshannon** [comment]
I think it's due to https://github.com/copier-org/copier/pull/1526 in the latest version of copier.

**Review by coretl — APPROVED** [review]

**Pull request merged**
