### PR TITLE
Add newlines at ends of files

### PR DESCRIPTION
**Pull request by GDYendell**
- [x] Depends on #140

### CODE REVIEW

**Comment by coretl** [comment]
The blank lines were removed because of the default VSCode formatting setting, I wonder if this still happens in a fresh profile?

**Comment by joeshannon** [comment]
Just to note that after running `end-of-file-fixer` on the HEAD of this PR there are actually quite a few other files in the project with no new line at EOF.

**Comment by coretl** [comment]
@joeshannon if you put `files.insertFinalNewline` in `.vscode/setting.json` does it respect it?

**Comment by joeshannon** [comment]
> @joeshannon if you put `files.insertFinalNewline` in `.vscode/setting.json` does it respect it?

Yes it does

**Comment by coretl** [comment]
Ok, so happy to accept this PR if we add that line in. Could also add the `end-of-file-fixer` while we're at it to make sure all files abide by this

**Comment by joeshannon** [comment]
> > @joeshannon if you put `files.insertFinalNewline` in `.vscode/setting.json` does it respect it?
> 
> Yes it does

Just to follow up: for "Format Document" it did take affect for the html formatting but didn't seem to for json, however it did change the behaviour to add the new line when saving the json file.

**Comment by GDYendell** [comment]
Thanks @joeshannon that looks good!

**Review by coretl — APPROVED** [review]
I think this is fine now, shall we merge?

**Comment by joeshannon** [comment]
I'm happy with it.

**Comment by coretl** [comment]
Hmm, we now get a failure:
https://github.com/DiamondLightSource/python-copier-template-example/actions/runs/9099023019/job/25010615685

Please can someone put in a PR to delete the extra lines at the end of README.jinja and Dockerfile.jinja?

**Comment by coretl** [comment]
Actually, I'll do this

**Comment by coretl** [comment]
https://github.com/DiamondLightSource/python-copier-template/pull/161

**Pull request merged**
